FROM python:3.11-slim

WORKDIR /backend

# 👇 ONLY copy backend folder contents
COPY backend/ .

RUN pip install --no-cache-dir -r requirements.txt

CMD sh -c "gunicorn src.app:app --bind 0.0.0.0:${PORT:-8000}"
